spring:

    datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/groupproject
    jooq:
        sql-dialect: org.hibernate.dialect.MySQL5Dialecte
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create


jpa:
    show-sql: true